apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: bdadzie
  labels:
    app: app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 20
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: feature-toggle
        - secretRef:
            name: db-secret
        name: app-deployment
        image: harbor.dev.afsmtddso.com/bdadzie-harbor-project/app@sha256:7aa499e6d5d2bb2526d7a4ca85ce193585d77b7d20a0dee98c051160c7a039a8
        ports:
        - containerPort: 500
