apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: bdadzie
  labels:
    app: db
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 20
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: db-secret
        name: db-deployment
        image: harbor.dev.afsmtddso.com/bdadzie-harbor-project/db@sha256:f170132f0ffdcbb4374b41593b913d3163da868d63afde2db9d8684dd3c1311d
        ports:
        - containerPort: 5432
